FROM nvidia/cuda:12.2.2-devel-ubuntu20.04
FROM python:3.8

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN apt-get update && apt-get install -y git
RUN pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install ftfy regex tqdm

#requirements.txtから依存パッケージをインストール
WORKDIR /work
COPY requirements.txt .
RUN pip3 install -r requirements.txt


ENV LIBRARY_PATH /usr/local/cuda/lib64/stub